import { Router } from 'express';
import { auth as authenticate } from './middlewares/auth.js';
import { router as authRoutes } from './modules/auth/routes.js';
import { router as pacientesRoutes } from './modules/pacientes/routes.js';
import { router as historiaclinicaRoutes } from './modules/historia-clinica/routes.js';
import { router as odontogramaRoutes } from './modules/odontograma/routes.js';
import { router as tratamientosRoutes } from './modules/tratamientos/routes.js';
import { router as pagosRoutes } from './modules/pagos/routes.js';
import { router as agendaRoutes } from './modules/agenda/routes.js';
import { router as dashboardRoutes } from './modules/dashboard/routes.js';
import { router as reportesRoutes } from './modules/reportes/routes.js';
export const api = Router();
api.use(authRoutes);
api.use(authenticate);
api.use(pacientesRoutes);
api.use(historiaclinicaRoutes);
api.use(odontogramaRoutes);
api.use(tratamientosRoutes);
api.use(pagosRoutes);
api.use(agendaRoutes);
api.use(dashboardRoutes);
api.use(reportesRoutes);
